<template>
    <div class="my-table-body-wrap">
      <scroll-view class="scroll" :pullUpLoad="true" :style="{height:height}" @pullingUp="loadData">
        <table width="100%" class="my-table-body">
          <colgroup>
            <col :width="colItem.width" v-for="(colItem,index) in columns">   <!--序号-->

          </colgroup>
          <tbody>
          <tr v-for="(item ,index ) in lists" :key="index">
            <td>{{item.id}}</td>
            <td>{{item.name}}</td>
            <td>{{item.sex}}</td>
            <td>{{item.age}}</td>
            <td>{{item.assessName}}（简版）</td>
            <td>{{item.score}}</td>
            <td>{{item.assessSource}}</td>
            <td>{{item.assessTime}}.09.14</td>
            <td>{{item.assessMan}}</td>
          </tr>



          </tbody>
        </table>
      </scroll-view>
    </div>
</template>

<script>
    export default {
      name:'MyTableBody',
      data(){
        return {
          lists:[
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            },
            {
              id:1,
              name:'张三',
              sex:'男',
              age:23,
              assessName:'图片记忆测验',
              score:40,
              assessSource:'基础脑健康评估',
              assessTime:'2018.09.12',
              assessMan:'张三'
            }
          ]
        }
      },
      props:{
        columns:{
          type:Array,
          default(){
            return []
          }
        }
      },
      computed:{
        height(){
          return this.$parent.height?this.$parent.height+'px':'auto'
        }
      },
      methods:{
        loadData(){
          console.log('加载更多')
        }
      }
    }
</script>

<style lang="scss" >
  .my-table-body{

    tr{
      height:120px;
      font-size:26px;/*px*/
      color:#5f5f5f;
    }
    tr:nth-of-type(odd){
      background-color:#f9fbff;
    }
    tr:nth-of-type(even){
      background-color:#f4f7fe;
    }
  }
  .scroll{
    overflow: hidden;
    position:relative;
  }
</style>
